*===============================================================================
* build_magnusweb_profit.do — Import MagnusWeb accounting ratios
*
* Module: 1_data (Gentzkow Lab template). Pure data-build script that
* reads raw MagnusWeb CSVs and writes a firm-year profitability panel
* consumed by 2_analysis downstream.
*
* Reads `ratios1-3.csv` (ID, Year, WVA, WS, LP, CM III) from the raw
* MagnusWeb export and builds a firm-year panel of profitability measures:
*
*   CM III — Contribution margin III (≈ EBIT ratio, the Czech standard
*            accounting EBIT measure: operating contribution after
*            overhead and administration costs, before financing)
*   WVA    — Wages / Value Added (labor share of VA)
*   WS     — Wages / Sales (labor share of sales)
*   LP     — Labour productivity (VA / employees)
*
* CM III is the primary profitability outcome for the reform-mechanism
* analysis: it's independent of our ACF markup construction and is the
* Czech accounting standard for operating profitability.
*
* Callers must set the `$data` global to the target output directory
* before calling this script. 1_data/make.sh sets it to 1_data/output;
* 2_analysis/source/stata/launcher.do sets it to 2_analysis/output/stata.
* The do-file is agnostic to which module runs it, and the relative
* input path resolves correctly from both caller locations because each
* is 3 levels deep under `markups-procurement/`.
*
* Input:  ../../../0_raw/magnusweb/ratios1.csv, ratios2.csv, ratios3.csv
* Output: $data/magnusweb_profit.dta
*===============================================================================

* Auto-set $data if caller did not (e.g., direct invocation from
* 1_data/source/stata/ with no wrapper). Default to sibling ../../output
* relative to this script's directory, matching the 1_data module output.
cap confirm existence "$data"
if _rc != 0 | "$data" == "" {
    global data "../../output"
    cap mkdir "$data"
}

dis _newline "--- build_magnusweb_profit.do ---"

tempfile master
clear
set obs 0
gen long id = .
gen int  year = .
gen double wva = .
gen double ws = .
gen double lp = .
gen double cm_iii = .
save `master'

foreach n in 1 2 3 {
    local fpath "../../../0_raw/magnusweb/ratios`n'.csv"
    cap confirm file "`fpath'"
    if _rc != 0 {
        dis "  SKIP ratios`n'.csv — file not found"
        continue
    }
    preserve
    * Use case(lower) so column names are deterministic across runs.
    * Stata's autogenerated names from the header row:
    *   id
    *   year
    *   wvawagesvalueadded        (from "WVA - Wages / Value added")
    *   wswagessales              (from "WS - Wages / Sales")
    *   lplabourproductivity      (from "LP - Labour productivity")
    *   cmiiicontributionmargin   (from "CM III - Contribution margin")
    import delimited "`fpath'", clear varn(1) bindquote(strict) ///
        stripquote(yes) case(lower)
    cap rename wvawagesvalueadded wva
    cap rename wswagessales ws
    cap rename lplabourproductivity lp
    cap rename cmiiicontributionmargin cm_iii
    cap destring wva ws lp cm_iii year id, replace force
    keep id year wva ws lp cm_iii
    drop if mi(id) | mi(year)
    append using `master'
    save `master', replace
    restore
}

use `master', clear
dis "  Total MagnusWeb ratio rows: " _N

* Deduplicate on id + year (source split across 3 CSVs may have overlaps)
duplicates drop id year, force
dis "  After id+year dedup: " _N

* Winsorize CM III and WVA at 2nd/98th percentile to handle the heavy tails
* in raw accounting-ratio data (extreme values arise from near-zero
* denominators in young firms and restructured balance sheets).
* NOTE: summarize,d does NOT return r(p2)/r(p98); use _pctile explicitly.
foreach v in cm_iii wva ws {
    _pctile `v', p(2 98)
    local lo = r(r1)
    local hi = r(r2)
    replace `v' = `lo' if `v' < `lo' & !mi(`v')
    replace `v' = `hi' if `v' > `hi' & !mi(`v')
}

sort id year
compress
save "$data/magnusweb_profit.dta", replace
dis "  Saved: magnusweb_profit.dta"

* Quick sanity check
qui summ cm_iii, d
dis "  CM III — mean " %7.2f r(mean) " min " %7.2f r(min) " max " %7.2f r(max) ///
    " n " r(N)
qui summ wva, d
dis "  WVA — mean " %7.2f r(mean) " min " %7.2f r(min) " max " %7.2f r(max) ///
    " n " r(N)
